### ISSUE TITLE
Unhandled Exception: System.AggregateException: One or more errors occurred

### ISSUE THREAD

**Issue by zimorodokan** [kerams/memrise-scraper#1]
I downloaded the last zip version from https://github.com/kerams/memrise-scraper/releases/tag/v1.0.1

D:\temp\MemriseScraper>MemriseScraper.exe 1096816
..........
Unhandled Exception: System.AggregateException: One or more errors occurred. ---> System.Exception: Unexpected column kind
at Program.mapping@1(String tupledArg0, JsonValue tupledArg1)
at Program.unifyColumnsAndAttributes(IJsonDocument thing)
at Program.main@127-1.Invoke(HtmlNode w)
at Microsoft.FSharp.Primitives.Basics.List.map[T,TResult](FSharpFunc2 mapping, FSharpList1 x)
at Program.main@120.Invoke(String level)
at Microsoft.FSharp.Collections.ArrayModule.Parallel.Map@1324-3.Invoke(Int32 i)
at System.Threading.Tasks.Parallel.<>c__DisplayClass17_01.<ForWorker>b__1() at System.Threading.Tasks.Task.InnerInvokeWithArg(Task childTask) at System.Threading.Tasks.Task.<>c__DisplayClass176_0.<ExecuteSelfReplicating>b__0(Object ) --- End of inner exception stack trace --- at System.Threading.Tasks.Task.ThrowIfExceptional(Boolean includeTaskCanceledExceptions) at System.Threading.Tasks.Task.Wait(Int32 millisecondsTimeout, CancellationToken cancellationToken) at System.Threading.Tasks.Parallel.ForWorker[TLocal](Int32 fromInclusive, Int32 toExclusive, ParallelOptions parallelOptions, Action1 body, Action2 bodyWithState, Func4 bodyWithLocal, Func1 localInit, Action1 localFinally)
at System.Threading.Tasks.Parallel.For(Int32 fromInclusive, Int32 toExclusive, Action1 body) at Microsoft.FSharp.Collections.ArrayModule.Parallel.Map[T,TResult](FSharpFunc2 mapping, T[] array)
at Program.main(String[] argv)

**Comment by kerams** [comment]
Thanks for the report. I've fixed the problem (videos in courses) and released v1.0.2.
