### ISSUE TITLE
Could not create SSL/TLS secure channel

### ISSUE THREAD

**Issue by zimorodokan** [kerams/memrise-scraper#5]
Hi!
I have got an error. This may be due to the fact that memrise uses a new programm interface.

`C:\Users\shain>D:\LEARN\Memrise\MemriseScraper\MemriseScraper.exe 332202

Unhandled Exception: System.Net.WebException: The request was aborted: Could not create SSL/TLS secure channel.
   at System.Net.HttpWebRequest.EndGetResponse(IAsyncResult asyncResult)
   at <StartupCode$FSharp-Core>.$Async.callback@1523.Invoke(IAsyncResult iar)
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at Microsoft.FSharp.Control.AsyncResult`1.Commit()
   at <StartupCode$FSharp-Core>.$Async.AwaitAndBindChildResult@1484-3.Invoke(Boolean _arg3)
   at Microsoft.FSharp.Control.AsyncPrimitives.CallThenInvokeNoHijackCheck[a,b](AsyncActivation`1 ctxt, FSharpFunc`2 userCode, b result1)
   at Microsoft.FSharp.Control.Trampoline.Execute(FSharpFunc`2 firstAction)
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at Microsoft.FSharp.Control.AsyncResult`1.Commit()
   at Microsoft.FSharp.Control.AsyncPrimitives.RunSynchronouslyInCurrentThread[a](CancellationToken cancellationToken, FSharpAsync`1 computation)
   at Microsoft.FSharp.Control.AsyncPrimitives.RunSynchronously[T](CancellationToken cancellationToken, FSharpAsync`1 computation, FSharpOption`1 timeout)
   at Microsoft.FSharp.Control.FSharpAsync.RunSynchronously[T](FSharpAsync`1 computation, FSharpOption`1 timeout, FSharpOption`1 cancellationToken)
   at Program.main(String[] argv)`

**Comment by kerams** [comment]
Thanks for the report. Memrise now uses certificates that require at least TLS 1.2. Grab the latest release and you're good to go.
